type IconClass =
    | 'icon-arrow-down'
    | 'icon-arrow-up'
    | 'icon-filter'
    | 'icon-sort'
    | 'icon-history'
    | 'icon-home'
    | 'icon-padlock'
    | 'icon-location-point'
    | 'icon-cart'
    | 'icon-user'
    | 'icon-search'
    | 'icon-map-marker'
    | 'icon-catalog'
    | 'icon-message'
    | 'icon-mail'
    | 'icon-phone'
    | 'icon-cross'
    | 'icon-check'
    | 'icon-odnoklasniki'
    | 'icon-vkontakte'
    | 'icon-telegram'
    | 'icon-youtube'
    | 'icon-minus'
    | 'icon-plus'
    | 'icon-heart-filled'
    | 'icon-heart'
    | 'icon-chevron-right-big'
    | 'icon-chevron-right'
    | 'icon-chevron-left-big'
    | 'icon-chevron-left'
    | 'icon-chevron-down'
    | 'icon-chevron-up';

export default IconClass;
